package p015cm.aptoide.p016pt;

import java.util.List;
import javax.inject.Provider;
import okhttp3.OkHttpClient;
import p015cm.aptoide.accountmanager.AdultContent;
import p015cm.aptoide.accountmanager.AptoideAccountManager;
import p015cm.aptoide.analytics.AnalyticsManager;
import p015cm.aptoide.analytics.implementation.navigation.NavigationTracker;
import p015cm.aptoide.p016pt.account.AdultContentAnalytics;
import p015cm.aptoide.p016pt.ads.AdsRepository;
import p015cm.aptoide.p016pt.ads.AdsUserPropertyManager;
import p015cm.aptoide.p016pt.analytics.FirstLaunchAnalytics;
import p015cm.aptoide.p016pt.database.RoomNotificationPersistence;
import p015cm.aptoide.p016pt.database.room.AptoideDatabase;
import p015cm.aptoide.p016pt.dataprovider.cache.L2Cache;
import p015cm.aptoide.p016pt.dataprovider.interfaces.TokenInvalidator;
import p015cm.aptoide.p016pt.dataprovider.p021ws.BodyInterceptor;
import p015cm.aptoide.p016pt.dataprovider.p021ws.p023v2.aptwords.AdsApplicationVersionCodeProvider;
import p015cm.aptoide.p016pt.dataprovider.p021ws.p025v7.BaseBody;
import p015cm.aptoide.p016pt.download.OemidProvider;
import p015cm.aptoide.p016pt.downloadmanager.AptoideDownloadManager;
import p015cm.aptoide.p016pt.file.CacheHelper;
import p015cm.aptoide.p016pt.file.FileManager;
import p015cm.aptoide.p016pt.install.AptoideInstalledAppsRepository;
import p015cm.aptoide.p016pt.install.InstallManager;
import p015cm.aptoide.p016pt.install.PackageRepository;
import p015cm.aptoide.p016pt.install.installer.RootInstallationRetryHandler;
import p015cm.aptoide.p016pt.networking.AuthenticationPersistence;
import p015cm.aptoide.p016pt.networking.IdsRepository;
import p015cm.aptoide.p016pt.notification.AptoideWorkerFactory;
import p015cm.aptoide.p016pt.notification.NotificationAnalytics;
import p015cm.aptoide.p016pt.notification.ReadyToInstallNotificationManager;
import p015cm.aptoide.p016pt.preferences.AptoideMd5Manager;
import p015cm.aptoide.p016pt.preferences.Preferences;
import p015cm.aptoide.p016pt.preferences.SecurePreferences;
import p015cm.aptoide.p016pt.root.RootAvailabilityManager;
import p015cm.aptoide.p016pt.search.suggestions.SearchSuggestionManager;
import p015cm.aptoide.p016pt.search.suggestions.TrendingManager;
import p015cm.aptoide.p016pt.store.StoreCredentialsProvider;
import p015cm.aptoide.p016pt.store.StoreUtilsProxy;
import p015cm.aptoide.p016pt.sync.SyncScheduler;
import p015cm.aptoide.p016pt.sync.alarm.SyncStorage;
import p015cm.aptoide.p016pt.themes.NewFeature;
import p015cm.aptoide.p016pt.themes.NewFeatureManager;
import p015cm.aptoide.p016pt.themes.ThemeAnalytics;
import p015cm.aptoide.p016pt.updates.UpdateRepository;
import p015cm.aptoide.p016pt.utils.p030q.QManager;
import p320o.C10822a;

/* renamed from: cm.aptoide.pt.NotificationApplicationView_MembersInjector */
public final class NotificationApplicationView_MembersInjector implements C10822a<NotificationApplicationView> {
    private final Provider<AptoideAccountManager> accountManagerProvider;

    /* renamed from: accountSettingsBodyInterceptorPoolV7AndBodyInterceptorPoolV7Provider */
    private final Provider<BodyInterceptor<BaseBody>> f3453xc59f298a;
    private final Provider<AdsRepository> adsRepositoryProvider;
    private final Provider<AdsUserPropertyManager> adsUserPropertyManagerProvider;
    private final Provider<AdultContentAnalytics> adultContentAnalyticsProvider;
    private final Provider<AdultContent> adultContentProvider;
    private final Provider<SyncScheduler> alarmSyncSchedulerProvider;
    private final Provider<AnalyticsManager> analyticsManagerProvider;
    private final Provider<AppCoinsManager> appCoinsManagerProvider;
    private final Provider<AppInBackgroundTracker> appInBackgroundTrackerProvider;
    private final Provider<AdsApplicationVersionCodeProvider> applicationVersionCodeProvider;
    private final Provider<AptoideDatabase> aptoideDatabaseProvider;
    private final Provider<AptoideDownloadManager> aptoideDownloadManagerProvider;
    private final Provider<AptoideInstalledAppsRepository> aptoideInstalledAppsRepositoryProvider;
    private final Provider<AptoideMd5Manager> aptoideMd5ManagerProvider;
    private final Provider<AptoideWorkerFactory> aptoideWorkerFactoryProvider;
    private final Provider<AuthenticationPersistence> authenticationPersistenceProvider;
    private final Provider<BodyInterceptor<p015cm.aptoide.p016pt.dataprovider.p021ws.p024v3.BaseBody>> bodyInterceptorV3Provider;
    private final Provider<BodyInterceptor<BaseBody>> bodyInterceptorWebV7Provider;
    private final Provider<CacheHelper> cacheHelperProvider;
    private final Provider<OkHttpClient> defaultClientProvider;
    private final Provider<List<String>> defaultFollowedStoresProvider;
    private final Provider<FileManager> fileManagerProvider;
    private final Provider<FirstLaunchAnalytics> firstLaunchAnalyticsProvider;
    private final Provider<L2Cache> httpClientCacheProvider;
    private final Provider<IdsRepository> idsRepositoryProvider;
    private final Provider<InstallManager> installManagerProvider;
    private final Provider<InvalidRefreshTokenLogoutManager> invalidRefreshTokenLogoutManagerProvider;
    private final Provider<LaunchManager> launchManagerProvider;
    private final Provider<NavigationTracker> navigationTrackerProvider;
    private final Provider<NewFeatureManager> newFeatureManagerProvider;
    private final Provider<NewFeature> newFeatureProvider;
    private final Provider<NotificationAnalytics> notificationAnalyticsProvider;
    private final Provider<RoomNotificationPersistence> notificationPersistenceProvider;
    private final Provider<OemidProvider> oemidProvider;
    private final Provider<PackageRepository> packageRepositoryProvider;
    private final Provider<Preferences> preferencesProvider;
    private final Provider<QManager> qManagerProvider;
    private final Provider<String> rakamBaseHostProvider;
    private final Provider<ReadyToInstallNotificationManager> readyToInstallNotificationManagerProvider;
    private final Provider<RootAvailabilityManager> rootAvailabilityManagerProvider;
    private final Provider<RootInstallationRetryHandler> rootInstallationRetryHandlerProvider;
    private final Provider<SearchSuggestionManager> searchSuggestionManagerProvider;
    private final Provider<SecurePreferences> securePreferencesProvider;
    private final Provider<SettingsManager> settingsManagerProvider;
    private final Provider<AptoideShortcutManager> shortcutManagerProvider;
    private final Provider<StoreCredentialsProvider> storeCredentialsProvider;
    private final Provider<StoreUtilsProxy> storeUtilsProxyProvider;
    private final Provider<SyncStorage> syncStorageProvider;
    private final Provider<ThemeAnalytics> themeAnalyticsProvider;
    private final Provider<TokenInvalidator> tokenInvalidatorProvider;
    private final Provider<TrendingManager> trendingManagerProvider;
    private final Provider<UpdateRepository> updateRepositoryProvider;

    public NotificationApplicationView_MembersInjector(Provider<AptoideDatabase> provider, Provider<RoomNotificationPersistence> provider2, Provider<AptoideInstalledAppsRepository> provider3, Provider<String> provider4, Provider<AptoideDownloadManager> provider5, Provider<UpdateRepository> provider6, Provider<CacheHelper> provider7, Provider<AptoideAccountManager> provider8, Provider<Preferences> provider9, Provider<SecurePreferences> provider10, Provider<AdultContent> provider11, Provider<IdsRepository> provider12, Provider<OkHttpClient> provider13, Provider<RootAvailabilityManager> provider14, Provider<AuthenticationPersistence> provider15, Provider<SyncScheduler> provider16, Provider<BodyInterceptor<BaseBody>> provider17, Provider<BodyInterceptor<BaseBody>> provider18, Provider<BodyInterceptor<p015cm.aptoide.p016pt.dataprovider.p021ws.p024v3.BaseBody>> provider19, Provider<L2Cache> provider20, Provider<QManager> provider21, Provider<TokenInvalidator> provider22, Provider<PackageRepository> provider23, Provider<AdsApplicationVersionCodeProvider> provider24, Provider<AdsRepository> provider25, Provider<SyncStorage> provider26, Provider<NavigationTracker> provider27, Provider<NewFeature> provider28, Provider<NewFeatureManager> provider29, Provider<ReadyToInstallNotificationManager> provider30, Provider<ThemeAnalytics> provider31, Provider<StoreCredentialsProvider> provider32, Provider<StoreUtilsProxy> provider33, Provider<TrendingManager> provider34, Provider<AdultContentAnalytics> provider35, Provider<NotificationAnalytics> provider36, Provider<SearchSuggestionManager> provider37, Provider<AnalyticsManager> provider38, Provider<FirstLaunchAnalytics> provider39, Provider<InvalidRefreshTokenLogoutManager> provider40, Provider<RootInstallationRetryHandler> provider41, Provider<AptoideShortcutManager> provider42, Provider<SettingsManager> provider43, Provider<InstallManager> provider44, Provider<List<String>> provider45, Provider<AdsUserPropertyManager> provider46, Provider<OemidProvider> provider47, Provider<AptoideMd5Manager> provider48, Provider<AptoideWorkerFactory> provider49, Provider<LaunchManager> provider50, Provider<AppInBackgroundTracker> provider51, Provider<AppCoinsManager> provider52, Provider<FileManager> provider53) {
        this.aptoideDatabaseProvider = provider;
        this.notificationPersistenceProvider = provider2;
        this.aptoideInstalledAppsRepositoryProvider = provider3;
        this.rakamBaseHostProvider = provider4;
        this.aptoideDownloadManagerProvider = provider5;
        this.updateRepositoryProvider = provider6;
        this.cacheHelperProvider = provider7;
        this.accountManagerProvider = provider8;
        this.preferencesProvider = provider9;
        this.securePreferencesProvider = provider10;
        this.adultContentProvider = provider11;
        this.idsRepositoryProvider = provider12;
        this.defaultClientProvider = provider13;
        this.rootAvailabilityManagerProvider = provider14;
        this.authenticationPersistenceProvider = provider15;
        this.alarmSyncSchedulerProvider = provider16;
        this.f3453xc59f298a = provider17;
        this.bodyInterceptorWebV7Provider = provider18;
        this.bodyInterceptorV3Provider = provider19;
        this.httpClientCacheProvider = provider20;
        this.qManagerProvider = provider21;
        this.tokenInvalidatorProvider = provider22;
        this.packageRepositoryProvider = provider23;
        this.applicationVersionCodeProvider = provider24;
        this.adsRepositoryProvider = provider25;
        this.syncStorageProvider = provider26;
        this.navigationTrackerProvider = provider27;
        this.newFeatureProvider = provider28;
        this.newFeatureManagerProvider = provider29;
        this.readyToInstallNotificationManagerProvider = provider30;
        this.themeAnalyticsProvider = provider31;
        this.storeCredentialsProvider = provider32;
        this.storeUtilsProxyProvider = provider33;
        this.trendingManagerProvider = provider34;
        this.adultContentAnalyticsProvider = provider35;
        this.notificationAnalyticsProvider = provider36;
        this.searchSuggestionManagerProvider = provider37;
        this.analyticsManagerProvider = provider38;
        this.firstLaunchAnalyticsProvider = provider39;
        this.invalidRefreshTokenLogoutManagerProvider = provider40;
        this.rootInstallationRetryHandlerProvider = provider41;
        this.shortcutManagerProvider = provider42;
        this.settingsManagerProvider = provider43;
        this.installManagerProvider = provider44;
        this.defaultFollowedStoresProvider = provider45;
        this.adsUserPropertyManagerProvider = provider46;
        this.oemidProvider = provider47;
        this.aptoideMd5ManagerProvider = provider48;
        this.aptoideWorkerFactoryProvider = provider49;
        this.launchManagerProvider = provider50;
        this.appInBackgroundTrackerProvider = provider51;
        this.appCoinsManagerProvider = provider52;
        this.fileManagerProvider = provider53;
    }

    public static C10822a<NotificationApplicationView> create(Provider<AptoideDatabase> provider, Provider<RoomNotificationPersistence> provider2, Provider<AptoideInstalledAppsRepository> provider3, Provider<String> provider4, Provider<AptoideDownloadManager> provider5, Provider<UpdateRepository> provider6, Provider<CacheHelper> provider7, Provider<AptoideAccountManager> provider8, Provider<Preferences> provider9, Provider<SecurePreferences> provider10, Provider<AdultContent> provider11, Provider<IdsRepository> provider12, Provider<OkHttpClient> provider13, Provider<RootAvailabilityManager> provider14, Provider<AuthenticationPersistence> provider15, Provider<SyncScheduler> provider16, Provider<BodyInterceptor<BaseBody>> provider17, Provider<BodyInterceptor<BaseBody>> provider18, Provider<BodyInterceptor<p015cm.aptoide.p016pt.dataprovider.p021ws.p024v3.BaseBody>> provider19, Provider<L2Cache> provider20, Provider<QManager> provider21, Provider<TokenInvalidator> provider22, Provider<PackageRepository> provider23, Provider<AdsApplicationVersionCodeProvider> provider24, Provider<AdsRepository> provider25, Provider<SyncStorage> provider26, Provider<NavigationTracker> provider27, Provider<NewFeature> provider28, Provider<NewFeatureManager> provider29, Provider<ReadyToInstallNotificationManager> provider30, Provider<ThemeAnalytics> provider31, Provider<StoreCredentialsProvider> provider32, Provider<StoreUtilsProxy> provider33, Provider<TrendingManager> provider34, Provider<AdultContentAnalytics> provider35, Provider<NotificationAnalytics> provider36, Provider<SearchSuggestionManager> provider37, Provider<AnalyticsManager> provider38, Provider<FirstLaunchAnalytics> provider39, Provider<InvalidRefreshTokenLogoutManager> provider40, Provider<RootInstallationRetryHandler> provider41, Provider<AptoideShortcutManager> provider42, Provider<SettingsManager> provider43, Provider<InstallManager> provider44, Provider<List<String>> provider45, Provider<AdsUserPropertyManager> provider46, Provider<OemidProvider> provider47, Provider<AptoideMd5Manager> provider48, Provider<AptoideWorkerFactory> provider49, Provider<LaunchManager> provider50, Provider<AppInBackgroundTracker> provider51, Provider<AppCoinsManager> provider52, Provider<FileManager> provider53) {
        return new NotificationApplicationView_MembersInjector(provider, provider2, provider3, provider4, provider5, provider6, provider7, provider8, provider9, provider10, provider11, provider12, provider13, provider14, provider15, provider16, provider17, provider18, provider19, provider20, provider21, provider22, provider23, provider24, provider25, provider26, provider27, provider28, provider29, provider30, provider31, provider32, provider33, provider34, provider35, provider36, provider37, provider38, provider39, provider40, provider41, provider42, provider43, provider44, provider45, provider46, provider47, provider48, provider49, provider50, provider51, provider52, provider53);
    }

    public void injectMembers(NotificationApplicationView notificationApplicationView) {
        AptoideApplication_MembersInjector.injectAptoideDatabase(notificationApplicationView, this.aptoideDatabaseProvider.get());
        AptoideApplication_MembersInjector.injectNotificationPersistence(notificationApplicationView, this.notificationPersistenceProvider.get());
        AptoideApplication_MembersInjector.injectAptoideInstalledAppsRepository(notificationApplicationView, this.aptoideInstalledAppsRepositoryProvider.get());
        AptoideApplication_MembersInjector.injectRakamBaseHost(notificationApplicationView, this.rakamBaseHostProvider.get());
        AptoideApplication_MembersInjector.injectAptoideDownloadManager(notificationApplicationView, this.aptoideDownloadManagerProvider.get());
        AptoideApplication_MembersInjector.injectUpdateRepository(notificationApplicationView, this.updateRepositoryProvider.get());
        AptoideApplication_MembersInjector.injectCacheHelper(notificationApplicationView, this.cacheHelperProvider.get());
        AptoideApplication_MembersInjector.injectAccountManager(notificationApplicationView, this.accountManagerProvider.get());
        AptoideApplication_MembersInjector.injectPreferences(notificationApplicationView, this.preferencesProvider.get());
        AptoideApplication_MembersInjector.injectSecurePreferences(notificationApplicationView, this.securePreferencesProvider.get());
        AptoideApplication_MembersInjector.injectAdultContent(notificationApplicationView, this.adultContentProvider.get());
        AptoideApplication_MembersInjector.injectIdsRepository(notificationApplicationView, this.idsRepositoryProvider.get());
        AptoideApplication_MembersInjector.injectDefaultClient(notificationApplicationView, this.defaultClientProvider.get());
        AptoideApplication_MembersInjector.injectRootAvailabilityManager(notificationApplicationView, this.rootAvailabilityManagerProvider.get());
        AptoideApplication_MembersInjector.injectAuthenticationPersistence(notificationApplicationView, this.authenticationPersistenceProvider.get());
        AptoideApplication_MembersInjector.injectAlarmSyncScheduler(notificationApplicationView, this.alarmSyncSchedulerProvider.get());
        AptoideApplication_MembersInjector.injectBodyInterceptorPoolV7(notificationApplicationView, this.f3453xc59f298a.get());
        AptoideApplication_MembersInjector.injectBodyInterceptorWebV7(notificationApplicationView, this.bodyInterceptorWebV7Provider.get());
        AptoideApplication_MembersInjector.injectBodyInterceptorV3(notificationApplicationView, this.bodyInterceptorV3Provider.get());
        AptoideApplication_MembersInjector.injectHttpClientCache(notificationApplicationView, this.httpClientCacheProvider.get());
        AptoideApplication_MembersInjector.injectQManager(notificationApplicationView, this.qManagerProvider.get());
        AptoideApplication_MembersInjector.injectTokenInvalidator(notificationApplicationView, this.tokenInvalidatorProvider.get());
        AptoideApplication_MembersInjector.injectPackageRepository(notificationApplicationView, this.packageRepositoryProvider.get());
        AptoideApplication_MembersInjector.injectApplicationVersionCodeProvider(notificationApplicationView, this.applicationVersionCodeProvider.get());
        AptoideApplication_MembersInjector.injectAdsRepository(notificationApplicationView, this.adsRepositoryProvider.get());
        AptoideApplication_MembersInjector.injectSyncStorage(notificationApplicationView, this.syncStorageProvider.get());
        AptoideApplication_MembersInjector.injectNavigationTracker(notificationApplicationView, this.navigationTrackerProvider.get());
        AptoideApplication_MembersInjector.injectNewFeature(notificationApplicationView, this.newFeatureProvider.get());
        AptoideApplication_MembersInjector.injectNewFeatureManager(notificationApplicationView, this.newFeatureManagerProvider.get());
        AptoideApplication_MembersInjector.injectReadyToInstallNotificationManager(notificationApplicationView, this.readyToInstallNotificationManagerProvider.get());
        AptoideApplication_MembersInjector.injectThemeAnalytics(notificationApplicationView, this.themeAnalyticsProvider.get());
        AptoideApplication_MembersInjector.injectAccountSettingsBodyInterceptorPoolV7(notificationApplicationView, this.f3453xc59f298a.get());
        AptoideApplication_MembersInjector.injectStoreCredentials(notificationApplicationView, this.storeCredentialsProvider.get());
        AptoideApplication_MembersInjector.injectStoreUtilsProxy(notificationApplicationView, this.storeUtilsProxyProvider.get());
        AptoideApplication_MembersInjector.injectTrendingManager(notificationApplicationView, this.trendingManagerProvider.get());
        AptoideApplication_MembersInjector.injectAdultContentAnalytics(notificationApplicationView, this.adultContentAnalyticsProvider.get());
        AptoideApplication_MembersInjector.injectNotificationAnalytics(notificationApplicationView, this.notificationAnalyticsProvider.get());
        AptoideApplication_MembersInjector.injectSearchSuggestionManager(notificationApplicationView, this.searchSuggestionManagerProvider.get());
        AptoideApplication_MembersInjector.injectAnalyticsManager(notificationApplicationView, this.analyticsManagerProvider.get());
        AptoideApplication_MembersInjector.injectFirstLaunchAnalytics(notificationApplicationView, this.firstLaunchAnalyticsProvider.get());
        AptoideApplication_MembersInjector.injectInvalidRefreshTokenLogoutManager(notificationApplicationView, this.invalidRefreshTokenLogoutManagerProvider.get());
        AptoideApplication_MembersInjector.injectRootInstallationRetryHandler(notificationApplicationView, this.rootInstallationRetryHandlerProvider.get());
        AptoideApplication_MembersInjector.injectShortcutManager(notificationApplicationView, this.shortcutManagerProvider.get());
        AptoideApplication_MembersInjector.injectSettingsManager(notificationApplicationView, this.settingsManagerProvider.get());
        AptoideApplication_MembersInjector.injectInstallManager(notificationApplicationView, this.installManagerProvider.get());
        AptoideApplication_MembersInjector.injectDefaultFollowedStores(notificationApplicationView, this.defaultFollowedStoresProvider.get());
        AptoideApplication_MembersInjector.injectAdsUserPropertyManager(notificationApplicationView, this.adsUserPropertyManagerProvider.get());
        AptoideApplication_MembersInjector.injectOemidProvider(notificationApplicationView, this.oemidProvider.get());
        AptoideApplication_MembersInjector.injectAptoideMd5Manager(notificationApplicationView, this.aptoideMd5ManagerProvider.get());
        AptoideApplication_MembersInjector.injectAptoideWorkerFactory(notificationApplicationView, this.aptoideWorkerFactoryProvider.get());
        AptoideApplication_MembersInjector.injectLaunchManager(notificationApplicationView, this.launchManagerProvider.get());
        AptoideApplication_MembersInjector.injectAppInBackgroundTracker(notificationApplicationView, this.appInBackgroundTrackerProvider.get());
        AptoideApplication_MembersInjector.injectAppCoinsManager(notificationApplicationView, this.appCoinsManagerProvider.get());
        AptoideApplication_MembersInjector.injectFileManager(notificationApplicationView, this.fileManagerProvider.get());
    }
}
