package org.parceler;

import android.os.Parcelable;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import org.parceler.NonParcelRepository;

/* renamed from: org.parceler.e */
/* compiled from: Parcels */
public final class C12420e {

    /* renamed from: a */
    private static final C12422b f32194a;

    /* renamed from: org.parceler.e$c */
    /* compiled from: Parcels */
    public interface C12423c<T> {
        /* renamed from: a */
        Parcelable mo40434a(T t);
    }

    /* renamed from: org.parceler.e$d */
    /* compiled from: Parcels */
    private static final class C12424d<T> implements C12423c<T> {

        /* renamed from: a */
        private final Constructor<? extends Parcelable> f32196a;

        public C12424d(Class<T> cls, Class<? extends Parcelable> cls2) {
            try {
                this.f32196a = cls2.getConstructor(new Class[]{cls});
            } catch (NoSuchMethodException e) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e);
            }
        }

        /* renamed from: a */
        public Parcelable mo40434a(T t) {
            try {
                return (Parcelable) this.f32196a.newInstance(new Object[]{t});
            } catch (InstantiationException e) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e);
            } catch (IllegalAccessException e2) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e2);
            } catch (InvocationTargetException e3) {
                throw new ParcelerRuntimeException("Unable to create ParcelFactory Type", e3);
            }
        }
    }

    static {
        C12422b bVar = new C12422b();
        f32194a = bVar;
        bVar.mo40473a((C12425f<C12423c>) NonParcelRepository.m40711a());
    }

    /* renamed from: a */
    public static <T> Parcelable m40843a(T t) {
        if (t == null) {
            return null;
        }
        return m40842a(t.getClass(), t);
    }

    /* renamed from: a */
    public static <T> Parcelable m40842a(Class<? extends T> cls, T t) {
        if (t == null) {
            return null;
        }
        return f32194a.mo40471a((Class) cls).mo40434a(t);
    }

    /* renamed from: a */
    public static <T> T m40844a(Parcelable parcelable) {
        if (parcelable == null) {
            return null;
        }
        return ((C12419d) parcelable).getParcel();
    }

    /* renamed from: org.parceler.e$b */
    /* compiled from: Parcels */
    private static final class C12422b {

        /* renamed from: a */
        private ConcurrentMap<Class, C12423c> f32195a;

        private C12422b() {
            this.f32195a = new ConcurrentHashMap();
        }

        /* renamed from: b */
        private static String m40845b(Class cls) {
            return cls.getName() + "$$" + "Parcelable";
        }

        /* renamed from: a */
        public C12423c mo40471a(Class cls) {
            C12423c cVar = (C12423c) this.f32195a.get(cls);
            if (cVar != null) {
                return cVar;
            }
            C12423c a = mo40472a(cls, cls.getClassLoader());
            if (Parcelable.class.isAssignableFrom(cls)) {
                a = new NonParcelRepository.C12405t();
            }
            if (a != null) {
                C12423c putIfAbsent = this.f32195a.putIfAbsent(cls, a);
                if (putIfAbsent == null) {
                    return a;
                }
                return putIfAbsent;
            }
            throw new ParcelerRuntimeException("Unable to find generated Parcelable class for " + cls.getName() + ", verify that your class is configured properly and that the Parcelable class " + m40845b(cls) + " is generated by Parceler.");
        }

        /* renamed from: a */
        public C12423c mo40472a(Class cls, ClassLoader classLoader) {
            try {
                return new C12424d(cls, classLoader.loadClass(m40845b(cls)));
            } catch (ClassNotFoundException unused) {
                return null;
            }
        }

        /* renamed from: a */
        public void mo40473a(C12425f<C12423c> fVar) {
            this.f32195a.putAll(fVar.get());
        }
    }
}
